apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: coreasp-deployment
spec:
  selector:
    matchLabels:
      app: coreasp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: coreasp
    spec:
      containers:
      - name: coreasp
        image: rcregistry.azurecr.io/coreasp:v1
        ports:
        - containerPort: 80